### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Yzs007** [hellloxiaotian/ESRGCNN#9]
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\ESRGCNN-main\train.py", line 56, in <module>
    main(cfg)
  File "C:\Users\DELL\Desktop\ESRGCNN-main\train.py", line 51, in main
    solver.fit()
  File "C:\Users\DELL\Desktop\ESRGCNN-main\solver.py", line 87, in fit
    sr = self.refiner(lr, scale).to(self.device)
  File "D:\anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DELL\Desktop\ESRGCNN-main\model\esrgcnn.py", line 113, in forward
    b1 = self.b1(x1)
  File "D:\anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DELL\Desktop\ESRGCNN-main\model\esrgcnn.py", line 53, in forward
    out1_r = self.ReLU(remain1)
  File "D:\anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "D:\anaconda3\envs\Pytorch\lib\site-packages\torch\nn\functional.py", line 1455, in relu
    result = torch.relu_(input)
RuntimeError: Output 1 of SplitWithSizesBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

您好，请问一下这是什么原因？

**Comment by hellloxiaotian** [comment]
请检查一下你的环境是否和我们的环境相同。此外，建议使用Ubuntu系统。

**Comment by Yzs007** [comment]
您好，我想请教一下一个问题。就是论文中用来对比的那些算法全都要自己跑一遍吗？ 还是用原作者得出的指标（PSNR/SSIM）和原作者的预训练模型？
